// Code generated by goctl. DO NOT EDIT.
// Source: gsecagent.proto

package gsecagentclient

import (
	"context"

	"github.com/lucheng0127/gsec/protoc/gsecagent"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	LoginRequest  = gsecagent.LoginRequest
	LoginResponse = gsecagent.LoginResponse

	Gsecagent interface {
		Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	}

	defaultGsecagent struct {
		cli zrpc.Client
	}
)

func NewGsecagent(cli zrpc.Client) Gsecagent {
	return &defaultGsecagent{
		cli: cli,
	}
}

func (m *defaultGsecagent) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := gsecagent.NewGsecagentClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}
