// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Username string `json:"username"`
	Token    string `json:"token"`
	Expire   int64  `json:"expire"`
}

type IpsecSA struct {
	ReqID string `json:"reqid"`
	Src   string `json:"src"`
	Dst   string `json:"dst"`
}

type IpsecRequest struct {
	ReqID string `json:"reqid,optional"`
	Src   string `json:"src,optional"`
	Dst   string `json:"dst,optional"`
}

type IpsecResponse struct {
	Data []IpsecSA `json:"data"`
}
