// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: agent/gsecagent.proto

package gsecagent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Gsecagent_Login_FullMethodName = "/gsecagent.Gsecagent/Login"
)

// GsecagentClient is the client API for Gsecagent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GsecagentClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type gsecagentClient struct {
	cc grpc.ClientConnInterface
}

func NewGsecagentClient(cc grpc.ClientConnInterface) GsecagentClient {
	return &gsecagentClient{cc}
}

func (c *gsecagentClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, Gsecagent_Login_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GsecagentServer is the server API for Gsecagent service.
// All implementations must embed UnimplementedGsecagentServer
// for forward compatibility
type GsecagentServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	mustEmbedUnimplementedGsecagentServer()
}

// UnimplementedGsecagentServer must be embedded to have forward compatible implementations.
type UnimplementedGsecagentServer struct {
}

func (UnimplementedGsecagentServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedGsecagentServer) mustEmbedUnimplementedGsecagentServer() {}

// UnsafeGsecagentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GsecagentServer will
// result in compilation errors.
type UnsafeGsecagentServer interface {
	mustEmbedUnimplementedGsecagentServer()
}

func RegisterGsecagentServer(s grpc.ServiceRegistrar, srv GsecagentServer) {
	s.RegisterService(&Gsecagent_ServiceDesc, srv)
}

func _Gsecagent_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GsecagentServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gsecagent_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GsecagentServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Gsecagent_ServiceDesc is the grpc.ServiceDesc for Gsecagent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Gsecagent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gsecagent.Gsecagent",
	HandlerType: (*GsecagentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Gsecagent_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent/gsecagent.proto",
}
